### ISSUE TITLE
add support for OpenEXR

### ISSUE THREAD

**Issue by twadleigh** [JuliaIO/ImageIO.jl#29]
I recently created [OpenEXR.jl](https://github.com/twadleigh/OpenEXR.jl) with a simple FileIO-compatible interface for loading/saving OpenEXR files.

I figure I might register it here on my way to getting it registered in FileIO. Before I do that, though, could someone explain to me the purpose of this package, vs. just registering the formats directly in FileIO?

**Comment by johnnychen94** [comment]
The main purpose of this package is to mimic the functionality of ImageMagick with small lightweight and fast Julia packages. Currently, both `ImageIO` and `ImageMagick` is added into Images.jl; eventually, we'll remove ImageMagick when `ImageIO` becomes comprehensive enough.

This package also provides a "strong" dependency management so that downstream consumers don't need to manually/explicitly manage the versions and names.

So one advantage is that once you register OpenEXR here, it gets shipped to all users of ImageIO without advertisement and package management.

**Comment by twadleigh** [comment]
Closed by #30.
